#!/usr/bin/env ansible-playbook
- hosts: Jiskerfet-gateways
  tasks:
    - name: unarchive backend
      unarchive:
        src: ./bin/Backend.tar
        dest: /home/jiskerfet-api/
        remote_src: no
        owner: jiskerfet-api
    - name: install dependencies of backend
      remote_user: jiskerfet-api
      npm: 
        path: /home/jiskerfet-api/Backend-Bookkeeping
    - name: Moving the config file to the backend
      template: src="./bin/config.json" dest="/home/jiskerfet-api/Backend-Bookkeeping/app/configuration_files/" 
      
- hosts: Jiskerfet-repository
  tasks:
    - name: Ensure the PostgreSQL service is running
      service: name=postgresql state=started enabled=yes
    - name: Create the user for the database 
      become: yes
      become_user: postgres
      postgresql_db: name=postgres
             encoding='UTF-8'
             lc_collate='en_US.UTF-8'
             lc_ctype='en_US.UTF-8'
             template='template0'
             state=present
    - name: quick test
      become: yes
      become_user: postgres
      postgresql_user: db=postgres
             name=postgres
             password=postgres
             priv=ALL
             state=present 
    - name: Replacing the sql file to create the tables in the database
      template: src="./bin/databasesetup.sql" dest="/home/databasesetup.sql"
    - name: Create new schema
      postgresql_schema:
         name: users
    - name: Execute the sql script
      become: true
      become_user: postgres
      command: psql -d postgres -a -f /home/databasesetup.sql
    - name: Deleting the sql file
      file:
         state: absent
         path: "/home/databasesetup.sql"
#    - name: start PM2 process
#      command: 'pm2 start -x -i 4 /home/jiskerfet-api/Backend-Bookkeeping/app/main.js'
#      ignore_errors: True
