#!/usr/bin/env ansible-playbook
- hosts: Jiskerfet-gateways
  tasks:
    # we don't want to run the jiskerfet API as root
    # this creates a user without root priviliges
    - name: Setup user that runs the api
      user:
        name: jiskerfet-api
        state: present
        shell: /bin/bash
        home: /home/jiskerfet-api
    - name: Setup epel release for nginx and nodejs
      yum: 
        name: epel-release
        state: latest
    - name: install nginx
      yum:
        name: nginx
        state: latest
    - name: start nginx
      systemd:
        state: started
        name: nginx
        enabled: yes

    - name: Creates the directory for nodejs
      file: path=/usr/local/lib/nodejs state=directory
    - name: Unarchive Nodejs
      unarchive:
        src: ./bin/nodejs-v8-11.3-linux-x64.tar.gz
        dest: /usr/local/lib/nodejs
        remote_src: no
        owner: jiskerfet-api
    - name: Create symbolic link node
      file:
        src: /usr/local/lib/nodejs/node-v8.11.3-linux-x64/bin/node
        dest: /usr/bin/node
        state: link
    - name: Create symbolic link npm
      file:
        src: /usr/local/lib/nodejs/node-v8.11.3-linux-x64/bin/npm
        dest: /usr/bin/npm
        state: link
#    - name: Set the enviroment variable for nodejs
#      shell: echo 'export NODEJS_HOME="/usr/local/lib/nodejs/node-v8.11.3-linux-x64/bin"' >> $HOME/.bashrc
#    - name: Set the Path for nodejs
#      shell: echo 'PATH="/usr/local/lib/nodejs/node-v8.11.3-linux-x64/bin:$PATH"' >> $HOME/.bashrc
    - name: install module for database
      yum:
       name: python-psycopg2
       state: latest 
# To daemonize the node application, we use pm2
    - name: install pm2
      npm:
        name: pm2
        version: latest
        global: yes
    - name: start pm2 on boot
      shell: sudo -u jiskerfet-api pm2 startup | bash
    - name: making sure pm2 is actually running
      systemd: 
        name: pm2-jiskerfet-api
        state: started
- hosts: Jiskerfet-repository
  tasks: 
    - name: install postgresql-server
      yum:
        name: postgresql-server
        state: latest
    - name: install postresql-contrib
      yum:
        name: postgresql-contrib
        state: latest

    
